### ISSUE TITLE
Something wrong with `valid-locator-type` rule

### ISSUE THREAD

**Issue by lucassus** [alecxe/eslint-plugin-protractor#56]
See https://travis-ci.org/lucassus/angular-webpack-seed/builds/175647512
and https://github.com/lucassus/angular-webpack-seed/blob/eslint-plugin-protractor-bug/e2e/.eslintrc.json

```
/Users/lucassus/Projects/OpenSource/angular-webpack-seed/node_modules/eslint-plugin-protractor/lib/rules/valid-locator-type.js:60
  return node.arguments && node.arguments[0].type === 'Literal'
                                            ^

TypeError: Cannot read property 'type' of undefined
    at isArgumentLiteral (/Users/lucassus/Projects/OpenSource/angular-webpack-seed/node_modules/eslint-plugin-protractor/lib/rules/valid-locator-type.js:60:45)
    at EventEmitter.CallExpression (/Users/lucassus/Projects/OpenSource/angular-webpack-seed/node_modules/eslint-plugin-protractor/lib/rules/valid-locator-type.js:110:37)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/Users/lucassus/Projects/OpenSource/angular-webpack-seed/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/lucassus/Projects/OpenSource/angular-webpack-seed/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/Users/lucassus/Projects/OpenSource/angular-webpack-seed/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/Users/lucassus/Projects/OpenSource/angular-webpack-seed/node_modules/eslint/lib/eslint.js:925:36)
    at Controller.__execute (/Users/lucassus/Projects/OpenSource/angular-webpack-seed/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/lucassus/Projects/OpenSource/angular-webpack-seed/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/Users/lucassus/Projects/OpenSource/angular-webpack-seed/node_modules/eslint/lib/util/traverser.js:36:33)
    at EventEmitter.module.exports.api.verify (/Users/lucassus/Projects/OpenSource/angular-webpack-seed/node_modules/eslint/lib/eslint.js:922:23)
    at processText (/Users/lucassus/Projects/OpenSource/angular-webpack-seed/node_modules/eslint/lib/cli-engine.js:264:31)
    at CLIEngine.executeOnText (/Users/lucassus/Projects/OpenSource/angular-webpack-seed/node_modules/eslint/lib/cli-engine.js:754:26)
    at verify (/Users/lucassus/Projects/OpenSource/angular-webpack-seed/node_modules/gulp-eslint/index.js:20:25)
    at Transform.util.transform [as _transform] (/Users/lucassus/Projects/OpenSource/angular-webpack-seed/node_modules/gulp-eslint/index.js:70:17)
```

**Comment by alecxe** [comment]
@lucassus thanks for the quick report. Should be fixed in 1.29.1, please try updating and let me know if the problem persists.
